devices:
  depo:
    s_positions:
      full_down: -283
      full_up: -2
    vol_deg_map:
      0.0: -3
      0.089: 114
      0.096: 106
      0.213: 199
      0.3: 257
      0.394: 327
      0.502: 420
      0.594: 490
      0.729: 601
    x_offset: -76
    y_offset: -188
  pH:
    pH_positions:
      full_down: -322
      full_up: 57
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.0.4
  pi2_address: 192.168.0.5
stage:
  aux_loc_map:
    acid:
    - -1282
    - -732
    base:
    - -1282
    - -261
    clean:
    - -1092
    - -454
  cell_loc_map: C:\Users\drago\Documents\Lab\GenGit\LEGOLAS-Files\cell_map.pkl
  home_x_offset: -100
  home_y_offset: -100
