devices:
  depo:
    s_positions:
      full_down: -136
      full_up: 139
    vol_deg_map:
      0.098: 79
      0.213: 189
      0.296: 245
      0.425: 356
      0.496: 417
      0.593: 490
      0.727: 600
    x_offset: -421
    y_offset: -157
  pH:
    pH_positions:
      full_down: -25
      full_up: 483
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.0.4
  pi2_address: 192.168.0.5
stage:
  aux_loc_map:
    acid:
    - -1558
    - -751
    base:
    - -1554
    - -182
    clean:
    - -1435
    - -469
  cell_loc_map: C:\Users\drago\Documents\GitHub\LEGOLAS-Files\cell_map.pkl
  home_x_offset: -100
  home_y_offset: -100
